
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
    user = User.create(name: "vdc", email: "vdc@gmail.com", password: "aaaaaa", password_confirmation: "aaaaaa")

# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Collection.create([
  { :nom => "The Big Bang Theory", :year => 2007, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Genre.create([
  { :name => "Comedy", :created_at => nil, :updated_at => nil }
], :without_protection => true )



Langue.create([
  { :name => "ENG", :created_at => nil, :updated_at => nil }
], :without_protection => true )



People.create([
  { :firstname => "Jim", :name => "Parsons", :birthdate => 24/03/1973, :role => "Actor", :created_at => nil, :updated_at => nil }
], :without_protection => true )



Review.create([
  { :message => "Awesome! Sheldon is simply the best!", :star_rating => 3.8, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Subtitle.create([
  { :name => "FR", :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :name => "mousquetaire", :email => "mous@svodbe.be", :password => "P@ssw0rd", :created_at => nil, :updated_at => nil }
], :without_protection => true )



Video.create([
  { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type => "Serie", :title => "Le Grillon des champs", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E02/bbts03E02.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "Leonard Hofstadter et Sheldon Cooper vivent en colocation à Pasadena, une ville de l'agglomération de Los Angeles.
Ce sont tous deux des physiciens surdoués, « geeks » de surcroît. C'est d'ailleurs autour de cela qu'est axée la majeure partie comique de la série. Ils partagent quasiment tout leur temps libre avec leurs deux amis Howard Wolowitz et Rajesh Koothrappali pour jouer à des jeux vidéo comme Halo, organiser un marathon des films Superman, jouer à des jeux de société ou de rôles comme le Boggle klingon, Donjons et Dragons, voire discuter de théories scientifiques très complexes. Leur univers routinier est perturbé lorsqu'une jolie jeune femme, Penny, s'installe dans l'appartement d’en face.
Leonard a immédiatement des vues sur elle, et va tout faire pour la séduire et l'intégrer au groupe et à leur univers auquel elle ne connaît rien.", :position => 2, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 3.8,
:created_at => nil, :updated_at => nil }
], :without_protection => true )

