# encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
    user = User.create(name: "vdc", email: "vince@gmail.com", password: "aaaaaa", password_confirmation: "aaaaaa")

# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

@cols = Collection.create([
  { :name => "The Big Bang Theory", :year => 2007, :created_at => nil, :updated_at => nil }
], :without_protection => true )

@genres = Genre.create([
  { :name => "Comedy", :created_at => nil, :updated_at => nil }
], :without_protection => true )


@langs = Langue.create([
  { :name => "ENG", :created_at => nil, :updated_at => nil }
], :without_protection => true )


@subs = Subtitle.create([
  { :name => "FR", :created_at => nil, :updated_at => nil }
], :without_protection => true )


User.create([
  { :name => "mousquetaire", :email => "mous@svodbe.be", :password => "P@ssw0rd", :password_confirmation => "P@ssw0rd",
    :created_at => nil, :updated_at => nil }
], :without_protection => true )



Video.create([
  { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type_video => "Serie", :title => "La fluctuation de l'ouvre-boîte électrique", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E01/bbts03E01.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "Sheldon rentre au Texas en disgrâce quand il apprend que ses camarades ont altéré les données de son expédition dans l'Arctique...", :position => 1, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 2.8,
    :collection => @cols.first, :langues => @langs, :subtitles => @subs, :genres => @genres,
  :created_at => nil, :updated_at => nil }],
  :without_protection => true )

Video.create([
  { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type_video => "Serie", :title => "Le Grillon des champs", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E02/bbts03E02.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "La première nuit de Leonard et Penny ne se déroule pas réellement comme ils l'imaginaient. Sheldon et Howard sont en désaccord sur la nature d'un criquet et décident de parier les comics auxquels ils tiennent le plus.", :position => 2, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 3.8,
    :collection => @cols.first, :langues => @langs, :subtitles => @subs, :genres => @genres,
    :created_at => nil, :updated_at => nil }],
    :without_protection => true )

Video.create([
  { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type_video => "Serie", :title => "La déviation Gotowitz", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E03/bbts03E03.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "Sheldon tente de faire retrouver à Penny sa bonne humeur avec des chocolats afin qu'elle soit plus gentille envers lui. Raj et Howard décident de s'habiller façon «gothique» afin d'aller draguer dans un night club.", :position => 3, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 3.8,
    :collection => @cols.first, :langues => @langs, :subtitles => @subs, :genres => @genres,
  :created_at => nil, :updated_at => nil }],
  :without_protection => true )

Video.create([
  { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type_video => "Serie", :title => "La solution pirate", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E04/bbts03E04.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "Raj apprend qu'il sera renvoyé en Inde s'il ne trouve pas du travail rapidement. Sheldon lui propose alors de travailler pour lui.", :position => 4, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 3.8,
    :collection => @cols.first, :langues => @langs, :subtitles => @subs, :genres => @genres,
  :created_at => nil, :updated_at => nil }],
  :without_protection => true )

Video.create([
                 { :thumbnail_url => "http://fanart.tv/fanart/tv/80379/seasonthumb/B_80379%20(3).jpg", :type_video => "Serie", :title => "Le tournoi de cartes", :year => 2009, :duration => 1380, :country => "USA", :video_url => "http://vps.vincex86.be/videos/bbt/3/bbts03E05/bbts03E05.ism/manifest", :bo_url => "http://www.wat.tv/video/the-big-bang-theory-bande-1upid_2exzl_.html", :synopsis => "Sheldon tente de faire retrouver à Penny sa bonne humeur avec des chocolats afin qu'elle soit plus gentille envers lui. Raj et Howard décident de s'habiller façon «gothique» afin d'aller draguer dans un night club.", :position => 5, :tagline => "humour#rire#sheldon#leaonard#tbbt#big#bang", :season => 3, :star_rating_avg => 4.5,
                   :collection => @cols.first, :langues => @langs, :subtitles => @subs, :genres => @genres,
                   :created_at => nil, :updated_at => nil }],
             :without_protection => true )


Video.create([
                 { :thumbnail_url => "", :type_video => "Film", :title => "Gladiator", :year => 2000, :duration => 155, :country => "USA", :video_url => "http://vps.vincex86.be/videos/Gladiator/Gladiator.ism/manifest", :bo_url => "", :synopsis => "Le général romain Maximus est le plus fidèle soutien de l'empereur Marc Aurèle, qu'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l'amour que lui voue l'empereur, le fils de MarcAurèle, Commode, s'arroge brutalement le pouvoir, puis ordonne l'arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le massacre de sa famille. Capturé par un marchand d'esclaves, il devient gladiateur et prépare sa vengeance.",
                   :position => 0, :tagline => "Péplum#Aventure#Drame#Action#Gladiator#", :season => 0, :star_rating_avg => 2,
                   :collection => @cols.nil?, :langues => @langs, :subtitles => @subs, :genres => @genres,
                   :created_at => nil, :updated_at => nil }],
             :without_protection => true )